### ISSUE TITLE
loading trained model fails

### ISSUE THREAD

**Issue by clstaudt** [raoulvm/reinforcement_mars_lander#2]
```
316 	: Episode || Reward:  378.10218689020974 	|| Average Reward:  198.23162853170285 	 epsilon:  0.2041345879004775
Landing Award granted
DQN Training Complete...
Traceback (most recent call last):
  File "mars_crane.py", line 249, in <module>
    trained_model = load_model(save_dir + "trained_model.h5")
  File "/Users/cls/miniforge3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/Users/cls/miniforge3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 182, in load_model_from_hdf5
    model_config = json_utils.decode(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

```
In [2]: tensorflow.__version__
Out[2]: '2.4.0-rc0'
```

**Comment by raoulvm** [comment]
Did you try to load a saved model from the repository or the model that was just saved by your own machine?

**Comment by clstaudt** [comment]
This happens eventually when running 
`>python mars_crane.py`

**Comment by raoulvm** [comment]
That is issue https://github.com/tensorflow/tensorflow/issues/44467 with a wrong h5py version, which is not pinned in your tensorflow branch.

**Comment by clstaudt** [comment]
Probably fixed by downgrade of `h5py`:  `>conda install h5py"<3.0.0"`
